export enum TYPES {
  WATER = "water",
  FIRE = "fire",
  GRASS = "grass",
  GROUND = "ground",
  ROCK = "rock",
  STEEL = "steel",
  ICE = "ice",
  ELECTRIC = "electric",
  DRAGON = "dragon",
  PSYCHIC = "psychic",
  NORMAL = "normal",
  FIGHTING = "fighting",
  POISON = "poison",
  BUG = "bug",
  FLYING = "flying",
  DARK = "dark",
  FAIRY = "fairy",
}
